# Generated by Django 5.1.5 on 2025-02-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('short_description', models.TextField(help_text='A brief summary of the project (max 250 characters)', max_length=250)),
                ('description', models.TextField()),
                ('technologies', models.CharField(help_text='Comma separated list of technologies used in the project(e.g. HTML, CSS, JavaScript)', max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio_images/')),
                ('testemonial', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
